name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - run: make build
